# Generated by Django 4.2.5 on 2023-09-25 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('image', models.ImageField(height_field='image_height', max_length=255, upload_to='uploads/products/', width_field='image_width')),
                ('image_height', models.PositiveIntegerField(blank=True, editable=False, null=True)),
                ('image_width', models.PositiveIntegerField(blank=True, editable=False, null=True)),
            ],
        ),
    ]
