# Generated by Django 4.2.5 on 2023-09-27 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_alter_product_image_height_alter_product_image_width'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='price',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
